import { definePreset } from './define.js';

const systemSans =
  'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';

/** Rounded corners, sentence-case labels and a cool neutral palette with a blue accent. */
export const soft = definePreset({
  name: 'soft',
  label: 'Soft',
  description: 'Rounded corners, sentence-case labels, cool neutrals and a blue accent.',
  density: 1.15,
  primitives: {
    typography: {
      display: systemSans,
      utility: systemSans,
      // Sentence case at 11px is harder to read than uppercase at 11px; give it the extra pixel.
      size: { xs: '0.75rem' },
    },
    borders: { radius: '6px' },
  },
  roles: {
    radiusControl: '6px',
    radiusInner: '4px',
    radiusSurface: '8px',
    radiusOverlay: '10px',
    labelTransform: 'none',
    labelTracking: '0em',
    labelTrackingWide: '0.02em',
    labelWeight: '500',
    controlTransform: 'none',
    controlTracking: '0em',
    controlWeight: '500',
    headingWeight: '600',
  },
  colors: {
    light: {
      background: '#f4f6f8',
      surface: '#ffffff',
      surfaceAlt: '#f8fafc',
      surfaceSunken: '#e9edf2',
      surfacePaper: '#ffffff',
      surfaceInverse: '#1c2430',
      surfaceInput: '#ffffff',
      text: '#1c2430',
      textMuted: '#556070',
      textInverse: '#f4f6f8',
      textAccent: '#1d4ed8',
      border: '#d5dbe3',
      borderSoft: '#e4e8ee',
      borderStrong: '#8792a2',
      borderControl: '#7b8696',
      borderSunken: '#d5dbe3',
      accent: '#2563eb',
      accentHover: '#1d4ed8',
      onAccent: '#ffffff',
      danger: '#c62828',
      dangerHover: '#a51d1d',
      onDanger: '#ffffff',
      textDanger: '#b42318',
      success: '#1f7a4d',
      onSuccess: '#ffffff',
      textSuccess: '#1a6a42',
      warning: '#a15c07',
      onWarning: '#ffffff',
      textWarning: '#8a4b06',
      info: '#0e6b8c',
      onInfo: '#ffffff',
      textInfo: '#0b5c78',
      focusRing: '#2563eb',
      shadowColor: '#1c2430',
    },
    dark: {
      background: '#11151b',
      surface: '#181d25',
      surfaceAlt: '#1e2430',
      surfaceSunken: '#0c0f13',
      surfacePaper: '#ffffff',
      surfaceInverse: '#e6eaf0',
      surfaceInput: '#1e2430',
      text: '#e6eaf0',
      textMuted: '#9aa5b4',
      textInverse: '#11151b',
      textAccent: '#8ab4ff',
      border: '#2d3542',
      borderSoft: '#232a35',
      borderStrong: '#5b6677',
      borderControl: '#6f7a8b',
      borderSunken: '#1f2630',
      accent: '#6aa1ff',
      accentHover: '#8ab4ff',
      onAccent: '#0c1220',
      danger: '#f07167',
      dangerHover: '#f4928a',
      onDanger: '#11151b',
      textDanger: '#f59a92',
      success: '#5cc08a',
      onSuccess: '#11151b',
      textSuccess: '#74cf9c',
      warning: '#e0a24a',
      onWarning: '#11151b',
      textWarning: '#e8b468',
      info: '#5bb5d6',
      onInfo: '#11151b',
      textInfo: '#7cc6e2',
      focusRing: '#8ab4ff',
      shadowColor: '#000000',
    },
  },
});
